version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/restaurant
    depends_on:
      - mongo
